---
- name: Install java
  apt:
    name: openjdk-8-jdk
    state: latest
    update_cache: true

- name: Install maven
  apt:
    name: maven
    state: latest

- name: Install pip
  apt:
    name: python3-pip
    state: latest

- name: Install dependencies
  pip:
    name: lxml
    state: present

- name: Deploy artifact
  maven_artifact:
    group_id: org.springframework.boot
    artifact_id: spring-boot-starter-parent
    version: "{{ release_version }}"
    repository_url: https://nexus.cb-demos.io/repository/maven-releases/
    extension: jar
    owner: "{{ target_user }}"
    username: "{{ nexus_user }}"
    password: "{{ nexus_password }}"
    dest: /tmp/webapp.jar

- name: Copy systemd service
  copy:
    src: webapp.service
    dest: /etc/systemd/system
    owner: root
    group: root

- name: Start service
  systemd:
    name: webapp
    state: started
    enabled: yes
