---
- name: create a disk
  gcp_compute_disk:
    name: "{{ instance_name }}-disk"
    size_gb: 20
    source_image: projects/ubuntu-os-cloud/global/images/family/ubuntu-1804-lts
    zone: us-east1-b
    project: "{{ gcp_project }}"
    auth_kind: "{{ gcp_cred_kind }}"
    service_account_file: "{{ gcp_cred_file }}"
    state: present
  register: disk

- name: create a network
  gcp_compute_network:
    name: "{{ instance_name }}-network"
    project: "{{ gcp_project }}"
    auth_kind: "{{ gcp_cred_kind }}"
    service_account_file: "{{ gcp_cred_file }}"
    state: present
  register: network

- name: create a address
  gcp_compute_address:
    name: "{{ instance_name }}-address"
    region: us-east1-b
    project: "{{ gcp_project }}"
    auth_kind: "{{ gcp_cred_kind }}"
    service_account_file: "{{ gcp_cred_file }}"
    state: present
  register: address

- name: Create firewall
  gcp_compute_firewall:
    name: "{{ instance_name }}-firewall"
    network: "{{ network }}"
    allowed:
      - ip_protocol: tcp
        ports: ['80', '22', '443', '8080']
    target_tags: my-instance
    source_ranges: ['0.0.0.0/0']
    project: "{{ gcp_project }}"
    auth_kind: "{{ gcp_cred_kind }}"
    service_account_file: "{{ gcp_cred_file }}"
    state: present
  register: firewall

- name: Create an instance
  gcp_compute_instance:
    name: "{{ instance_name }}"
    machine_type: n1-standard-1
    zone: us-east1-b
    project: "{{ gcp_project }}"
    state: present
    auth_kind: "{{ gcp_cred_kind }}"
    service_account_file: "{{ gcp_cred_file }}"
    tags:
      items:
        - my-instance
    disks:
      - auto_delete: true
        boot: 'true'
        source: "{{ disk }}"
    network_interfaces:
      - network: "{{ network }}"
        access_configs:
          - name: External NAT
            nat_ip: "{{ address }}"
            type: ONE_TO_ONE_NAT
  register: instance

- name: Wait for SSH to come up
  wait_for: host={{ address.address }} port=22 delay=10 timeout=180

- name: Add host to groupname
  add_host:
    hostname: "{{ address.address }}"
    groupname: new_instances
